In [1]:
import pandas as pd 
import numpy as np 
import fcsparser
import torch
from torch.utils.data import TensorDataset, DataLoader, Subset
import random
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.nn.functional as F
from scipy.stats import zscore
from torch.autograd import Variable



In [2]:
healthy_covid_patients = ['export_COVID19 samples 23_04_20_ST3_COVID19_HC_001 ST3 230420_017_Live_cells.fcs',  'export_COVID19 samples 23_04_20_ST3_COVID19_HC_005 ST3 230420_016_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_HC_006 ST3 230420_015_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_HC_007 ST3 230420_014_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_HC_008 ST3 230420_013_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_HC_009 ST3 230420_012_Live_cells.fcs']

ward_covid_patient = ['export_COVID19 samples 21_04_20_ST3_COVID19_ICU_changedW_019_O ST3 210420_040_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_changedW_027_O ST3 210420_039_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_changedW_036_O ST3 210420_035_Live_cells.fcs'  ,'export_COVID19 samples 21_04_20_ST3_COVID19_W_033_O ST3 210420_036_Live_cells.fcs',  'export_COVID19 samples 21_04_20_ST3_COVID19_W_042_O ST3 210420_032_Live_cells.fcs'  ,'export_COVID19 samples 21_04_20_ST3_COVID19_W_043_O ST3 210420_031_Live_cells.fcs',  'export_COVID19 samples 23_04_20_ST3_COVID19_W_001_O ST3 230420_037_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_010_O ST3 230420_033_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_011_O ST3 230420_032_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_012_O ST3 230420_031_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_014_O ST3 230420_029_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_015_O ST3 230420_028_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_016_O ST3 230420_027_Live_cells.fcs'  , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_017_O ST3 230420_026_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_018_O ST3 230420_025_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_020_O ST3 230420_007_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_022_O ST3 230420_006_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_024_O ST3 230420_005_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_025_O ST3 230420_004_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_026_O ST3 230420_003_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_029_O ST3 230420_002_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_046_O ST3 230420_011_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_W_048_O ST3 230420_010_Live_cells.fcs']

ICU_covid_patient =['export_COVID19 samples 21_04_20_ST3_COVID19_ICU_005_A ST3 210420_080_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_013_A ST3 210420_078_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_014_A ST3 210420_073_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_015_A ST3 210420_069_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_023_A ST3 210420_064_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_027_A ST3 210420_061_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_029_A ST3 210420_059_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_031_A ST3 210420_055_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_036_A ST3 210420_053_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_039_A ST3 210420_051_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_043_A ST3 210420_049_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_045_A ST3 210420_045_Live_cells.fcs' , 'export_COVID19 samples 21_04_20_ST3_COVID19_ICU_changedW_002_O ST3 210420_043_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_ICU_002_A ST3 230420_052_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_ICU_003_A ST3 230420_049_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_ICU_006_A ST3 230420_046_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_ICU_012_A ST3 230420_043_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_ICU_025_A ST3 230420_039_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_ICU_changedW_004_O ST3 230420_036_Live_cells.fcs' , 'export_COVID19 samples 23_04_20_ST3_COVID19_ICU_changedW_049_O ST3 230420_009_Live_cells.fcs']

In [3]:
PATH = 'C:/Users/admin/Desktop/FlowRepository_FR-FCM-Z2KP_files'

threshold_number_cell = 3000
healthy_patients = []
for patient in healthy_covid_patients:
    path = PATH + '/%s'%patient
    meta, patient_file = fcsparser.parse(path, reformat_meta=True)
    patient_file.drop(['FSC-A',	'FSC-H',	'FSC-W',	'SSC-A',	'SSC-H',	'SSC-W', 'Time'], axis = 1, inplace = True)
    if patient_file.shape[0] > threshold_number_cell:
        healthy_patients.append(patient_file.apply(zscore).to_numpy())
        print(patient_file.shape)

ward_patients = []
for patient in ward_covid_patient:
    path = PATH + '/%s'%patient
    meta, patient_file = fcsparser.parse(path, reformat_meta=True)
    patient_file.drop(['FSC-A',	'FSC-H',	'FSC-W',	'SSC-A',	'SSC-H',	'SSC-W', 'Time'], axis = 1, inplace = True)
    if patient_file.shape[0] > threshold_number_cell:
        ward_patients.append(patient_file.apply(zscore).to_numpy())
        print(patient_file.shape)

ICU_patients = []
for patient in ICU_covid_patient:
    path = PATH + '/%s'%patient
    meta, patient_file = fcsparser.parse(path, reformat_meta=True)
    patient_file.drop(['FSC-A',	'FSC-H',	'FSC-W',	'SSC-A',	'SSC-H',	'SSC-W', 'Time'], axis = 1, inplace = True)
    if patient_file.shape[0] > threshold_number_cell:
        ICU_patients.append(patient_file.apply(zscore).to_numpy())
        print(patient_file.shape)


(315187, 28)
(363314, 28)
(311492, 28)
(183001, 28)
(298047, 28)
(248917, 28)
(16808, 28)
(4683, 28)
(137169, 28)
(365508, 28)
(235332, 28)
(245734, 28)
(27390, 28)
(155175, 28)
(13767, 28)
(22520, 28)
(98608, 28)
(68610, 28)
(17164, 28)
(186246, 28)
(337833, 28)
(266928, 28)
(193497, 28)
(15778, 28)
(83002, 28)
(13728, 28)
(123154, 28)
(364473, 28)
(18618, 28)
(170075, 28)
(15792, 28)
(139037, 28)
(329393, 28)
(185298, 28)
(36744, 28)
(271522, 28)
(78856, 28)
(61226, 28)
(163885, 28)
(173816, 28)
(10959, 28)
(17412, 28)
(29363, 28)
(10127, 28)
(20956, 28)
(58691, 28)


In [4]:
all_patient = healthy_patients +  ward_patients + ICU_patients

In [5]:
status = []

for i in range(len(healthy_patients)):
    status.append(0)
for i in range(len(ward_patients)):
    status.append(1)
for i in range(len(ICU_patients)):
    status.append(2)
  

In [6]:
bin_nums = ((np.array(status).reshape(-1,1) & (np.arange(3))) != 0).astype(int)
print(bin_nums)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [7]:
subset_all_patient = [torch.from_numpy(item[:3000]).float() for item in all_patient]
subset_all_patient_torch = torch.stack(subset_all_patient).to(device ='cuda')




In [8]:
all_patient_status = [torch.from_numpy(item).float() for item in bin_nums]
all_patient_status_torch = torch.stack(all_patient_status).to(device ='cuda')#.unsqueeze(0)
all_patient_status_torch.size()

torch.Size([46, 3])

In [9]:
print(subset_all_patient_torch.size(),all_patient_status_torch.size())

torch.Size([46, 3000, 28]) torch.Size([46, 3])


In [10]:
dataset_covid_patients = TensorDataset(subset_all_patient_torch,all_patient_status_torch)

In [11]:
n = len(dataset_covid_patients)  # how many total elements you have
n_test = int( n * 0.4 )  # number of test/val elements
n_train = n - 4 * n_test
idx = list(range(n))  # indices to all elements
random.shuffle(idx)  # in-place shuffle the indices to facilitate random splitting
train_idx = idx[:n_train]
val_idx = idx[n_train:(n_train + n_test)]
test_idx = idx[(n_train + n_test):]

train_set = Subset(dataset_covid_patients, train_idx)
val_set = Subset(dataset_covid_patients, val_idx)
test_set = Subset(dataset_covid_patients, test_idx)

In [12]:
train_set_covid = DataLoader(dataset=train_set, shuffle=True)
val_set_covid = DataLoader(dataset=val_set, shuffle=True)
test_set_covid = DataLoader(dataset=test_set, shuffle=True)

In [35]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv1d(in_channels = 3000, out_channels = 28, kernel_size = 5 , stride=1)
        self.conv2 = nn.Conv1d(28, 1, 1)
        self.fc1 = nn.Linear(24, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 3)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        return x


net = Net().cuda()

In [36]:
for param in net.parameters():
    print(param.size())

torch.Size([28, 3000, 5])
torch.Size([28])
torch.Size([1, 28, 1])
torch.Size([1])
torch.Size([120, 24])
torch.Size([120])
torch.Size([84, 120])
torch.Size([84])
torch.Size([3, 84])
torch.Size([3])


In [39]:
print(net)

Net(
  (conv1): Conv1d(3000, 28, kernel_size=(5,), stride=(1,))
  (conv2): Conv1d(28, 1, kernel_size=(1,), stride=(1,))
  (fc1): Linear(in_features=24, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=3, bias=True)
)


In [40]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [41]:
for epoch in range(10):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(train_set_covid, 0):
        device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

        inputs, labels = data
        inputs, labels = inputs.to(device), labels.to(device)

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs.squeeze(0), labels.long())
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training') 

RuntimeError: multi-target not supported at C:/cb/pytorch_1000000000000/work/aten/src\THCUNN/generic/ClassNLLCriterion.cu:15

In [42]:
outputs.squeeze(0).size()

torch.Size([1, 3])

In [45]:
outputs.squeeze()

tensor([[0.0256, 0.0000, 0.0000]], device='cuda:0', grad_fn=<SqueezeBackward1>)

In [43]:
labels.long().size()

torch.Size([1, 3])

In [21]:
outputs.squeeze(0)

tensor([[-0.0653,  0.1301, -0.0273]], device='cuda:0',
       grad_fn=<SqueezeBackward1>)

In [29]:
labels.squeeze(0).long().size()

torch.Size([3])

In [39]:
outputs.squeeze().size()

torch.Size([3])

In [45]:
outputs.squeeze().round()

tensor([-0., 0., -0.], device='cuda:0', grad_fn=<RoundBackward>)

In [46]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)

In [33]:
class Simple1DCNN(torch.nn.Module):
    def __init__(self):
        super(Simple1DCNN, self).__init__()
        self.layer1 = torch.nn.Conv1d(in_channels=3000, out_channels=28, kernel_size=5, stride=1)
        self.layer2 = torch.nn.Conv1d(in_channels=28, out_channels=1, kernel_size=1)
        self.fc1 = nn.Linear(24, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 2)

    def forward(self, x):
        x = F.relu(self.layer1(x))
        x = F.relu(self.layer2(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))


        return x


model = Simple1DCNN().cuda()
print(model(inputs).shape)

torch.Size([1, 1, 2])


In [34]:
model(inputs)

tensor([[[0.0000, 0.1326]]], device='cuda:0', grad_fn=<ReluBackward0>)

In [47]:
input.size()

torch.Size([3, 5])

In [49]:
target.size()

torch.Size([3])

In [50]:
output = criterion(input, target)

In [51]:
output

tensor(1.2279, grad_fn=<NllLossBackward>)

In [76]:
outputs.squeeze().size()

torch.Size([2])

In [42]:
outputs.size()

torch.Size([1, 1, 3])

In [41]:
labels.size()

torch.Size([1, 3])